---
- name: OpenVPN | Harden | sysctl configuration
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'net.ipv4.conf.all.send_redirects', value: 0 }
    - { name: 'net.ipv4.conf.default.send_redirects', value: 0 }
    - { name: 'net.ipv4.conf.all.accept_redirects', value: 0 }
    - { name: 'net.ipv4.conf.default.accept_redirects', value: 0 }
    - { name: 'net.ipv6.conf.all.accept_redirects', value: 0 }
    - { name: 'net.ipv6.conf.default.accept_redirects', value: 0 }
    - { name: 'net.ipv4.conf.all.secure_redirects', value: 0 }
    - { name: 'net.ipv4.conf.default.secure_redirects', value: 0 }
    - { name: 'net.ipv4.icmp_echo_ignore_all', value: 1 }
    - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: 1 }
    - { name: 'net.ipv4.icmp_ignore_bogus_error_responses', value: 1 }
    - { name: 'net.ipv4.tcp_syncookies', value: 1 }
    - { name: 'net.ipv4.conf.all.rp_filter', value: 1 }
    - { name: 'net.ipv4.conf.default.rp_filter', value: 1 }
    - { name: 'kernel.core_uses_pid', value: 1 }
    - { name: 'kernel.sysrq', value: 0 }
    - { name: 'kernel.randomize_va_space', value: 2 }
    - { name: 'net.ipv4.conf.all.log_martians', value: 1 }
    - { name: 'net.ipv4.conf.default.log_martians', value: 1 }
    - { name: 'net.ipv4.conf.all.accept_source_route', value: 0 }
    - { name: 'net.ipv4.conf.default.accept_source_route', value: 0 }
    - { name: 'net.ipv4.tcp_timestamps', value: 0 }
    - { name: 'net.ipv6.conf.all.disable_ipv6', value: 1 }
    - { name: 'net.ipv6.conf.default.disable_ipv6', value: 1 }
    - { name: 'net.ipv6.conf.lo.disable_ipv6', value: 1 }
    - { name: 'net.ipv6.conf.default.accept_ra', value: 0 }
    - { name: 'fs.suid_dumpable', value: 0 }
    
