---
- name: Audit | OpenSCAP | Install
  package:
    name: "{{ item }}"
  with_items: "{{ audit_oscap_packages }}"

- name: Audit | OpenSCAP | Get SSGs from OpenSCAP github 
  get_url:
    url: "{{ oscap_ssg_url }}" 
    dest: "~/"
  when: ansible_os_family == "Debian"

- name: Audit | OpenSCAP | Unarchive OpenSCAP SSGs
  unarchive:
    src: "~/{{ oscap_ssg_archive }}"
    dest: "{{ oscap_policy_parent }}"
    remote_src: True
  when: ansible_os_family == "Debian"

- name: Audit | OpenSCAP | Run
  shell: >
    oscap xccdf eval
    --profile {{ item.profile }}
    --check-engine-results --oval-results
    --results ~/oscap_results_{{ item.name }}.xml
    --report ~/oscap_report_{{ item.name }}.html
    {{ item.extra }}
    {{ item.policy }}
  ignore_errors: true
  with_items: "{{ oscap_reports }}"
  register: openscap_results
  changed_when: false
  failed_when: false
  tags:
    - skip_ansible_lint

- name: Audit | OpenSCAP | Check Run Results
  fail:
    msg: "Error occurred. See stdout:\n{{ item.stdout }}"
  no_log: True
  when: item.stdout.find('OpenSCAP Error') == 1
  with_items: "{{ openscap_results.results }}"

- name: Audit | OpenSCAP | Make local destination
  local_action: file path="{{ local_creds_folder }}/" state=directory
  become: False

- name: Audit | OpenSCAP | Get report
  fetch:
    src: "~/oscap_report_{{ item.name }}.html"
    dest: "{{ local_creds_folder }}/oscap_report_{{ item.name }}.html"
    flat: yes
  with_items: "{{ oscap_reports }}"
