- name: Audit Server
# ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: "{{ cmd_hosts | default('openvpn-vpn') }}"

  roles:
    - audit
