- name: Install required software, configure and harden
# ========================================================
  hosts: openvpn-internet

# You need a python 2 interpreter first, so skip gathering facts, then use
# 'setup:' to get them after the python 2 interpreter has been installed.
# See 'pre_tasks' below
  gather_facts: no
  pre_tasks:
    # If python doesn't exist on path (type returns non-zero), install python
    - name: OpenVPN | install | Install python2 if necessary
      raw: 'type python >/dev/null 2>&1 || apt-get -y install python-minimal'
      changed_when: false

    - name: OpenVPN | install | Gather facts after python2 is available
      setup:

  roles:
    - openvpn
    - {role: add_clients, clients_to_add: "{{ openvpn_clients }}"}
    - {role: audit, when: do_audit is defined and do_audit }

  post_tasks:
    - name: OpenVPN | install | Restart system after setup
      shell: sleep 2 && shutdown -r now "Restart for OpenVPN install"
      async: 1
      poll: 0
      ignore_errors: true
      changed_when: false
      when: ansible_virtualization_type != "docker"
